/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum_29062026;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS VIVOBOOK
 */
public class FormMinuman extends javax.swing.JFrame {

    private FormUtama utama;
    public FormMinuman() {
        initComponents();
    }

    public FormMinuman(FormUtama utama) throws HeadlessException {
        this.utama = utama;
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbkEsjeruk = new javax.swing.JCheckBox();
        cbkEsteh = new javax.swing.JCheckBox();
        cbkKopsus = new javax.swing.JCheckBox();
        txtEsjeruk = new javax.swing.JTextField();
        txtEsteh = new javax.swing.JTextField();
        txtKopsus = new javax.swing.JTextField();
        cbEsjeruk = new javax.swing.JComboBox<>();
        cbEsteh = new javax.swing.JComboBox<>();
        cbKopsus = new javax.swing.JComboBox<>();
        txtTotEsjeruk = new javax.swing.JTextField();
        txtTotEsteh = new javax.swing.JTextField();
        txtTotKopsus = new javax.swing.JTextField();
        btnTotal = new javax.swing.JButton();
        txtTotalMinuman = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("PILIHAN MENU MINUMAN");

        cbkEsjeruk.setText("Es Jeruk");
        cbkEsjeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkEsjerukActionPerformed(evt);
            }
        });

        cbkEsteh.setText("Es Teh Manis");
        cbkEsteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkEstehActionPerformed(evt);
            }
        });

        cbkKopsus.setText("Kopi Susu");
        cbkKopsus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkKopsusActionPerformed(evt);
            }
        });

        txtEsjeruk.setText("0");
        txtEsjeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEsjerukActionPerformed(evt);
            }
        });

        txtEsteh.setText("0");
        txtEsteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstehActionPerformed(evt);
            }
        });

        txtKopsus.setText("0");
        txtKopsus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKopsusActionPerformed(evt);
            }
        });

        cbEsjeruk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbEsjeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEsjerukActionPerformed(evt);
            }
        });

        cbEsteh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbEsteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstehActionPerformed(evt);
            }
        });

        cbKopsus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbKopsus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKopsusActionPerformed(evt);
            }
        });

        txtTotEsjeruk.setText("0");

        txtTotEsteh.setText("0");

        txtTotKopsus.setText("0");

        btnTotal.setText("Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        txtTotalMinuman.setText("0");

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(302, 302, 302)
                                .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbkKopsus, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtKopsus, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cbkEsteh, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtEsteh, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cbkEsjeruk, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(txtEsjeruk, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbEsjeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbEsteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbKopsus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotEsjeruk, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(txtTotEsteh)
                            .addComponent(txtTotKopsus, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTotalMinuman))))
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addGap(256, 256, 256))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbkEsjeruk)
                    .addComponent(txtEsjeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEsjeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotEsjeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbkEsteh)
                    .addComponent(txtEsteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEsteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotEsteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbkKopsus)
                    .addComponent(txtKopsus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbKopsus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotKopsus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotal)
                    .addComponent(txtTotalMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(btnKembali)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEsjerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEsjerukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEsjerukActionPerformed

    private void txtEstehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstehActionPerformed

    private void txtKopsusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKopsusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKopsusActionPerformed

    private void cbEsjerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEsjerukActionPerformed
        int jumlah = (int) cbEsjeruk.getSelectedIndex();
        double harga =Double.parseDouble(txtEsjeruk.getText());
        double total = jumlah*harga;
        txtTotEsjeruk.setText(Double.toString(total));
    }//GEN-LAST:event_cbEsjerukActionPerformed

    private void cbEstehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstehActionPerformed
        int jumlah = (int) cbEsteh.getSelectedIndex();
        double harga =Double.parseDouble(txtEsteh.getText());
        double total = jumlah*harga;
        txtTotEsteh.setText(Double.toString(total));
    }//GEN-LAST:event_cbEstehActionPerformed

    private void cbKopsusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKopsusActionPerformed
        int jumlah = (int) cbKopsus.getSelectedIndex();
        double harga =Double.parseDouble(txtKopsus.getText());
        double total = jumlah*harga;
        txtTotKopsus.setText(Double.toString(total));
    }//GEN-LAST:event_cbKopsusActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        if (cbkEsjeruk.isSelected() && cbEsjeruk.getSelectedIndex() == 0) {JOptionPane.showMessageDialog(this,
            "Silakan pilih jumlah Es Jeruk","Peringatan",JOptionPane.WARNING_MESSAGE);
            cbEsjeruk.requestFocus();
        }

        if (cbkEsteh.isSelected() && cbEsteh.getSelectedIndex() == 0) {JOptionPane.showMessageDialog(this,
            "Silakan pilih jumlah Es Teh Manis","Peringatan",JOptionPane.WARNING_MESSAGE);
            cbEsteh.requestFocus();
        }

        if (cbkKopsus.isSelected() && cbKopsus.getSelectedIndex() == 0) {JOptionPane.showMessageDialog(this,
            "Silakan pilih jumlah Kopi Susu","Peringatan",JOptionPane.WARNING_MESSAGE);
            cbKopsus.requestFocus();
        }
        double a = Double.parseDouble(txtTotEsjeruk.getText());
        double b = Double.parseDouble(txtTotEsteh.getText());
        double c = Double.parseDouble(txtTotKopsus.getText());
        double total = a+b+c;
        txtTotalMinuman.setText(Double.toString(total));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String total = txtTotalMinuman.getText();
        utama.setTotalMinuman(total);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void cbkEsjerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkEsjerukActionPerformed
        txtEsjeruk.setText("8000");
    }//GEN-LAST:event_cbkEsjerukActionPerformed

    private void cbkEstehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkEstehActionPerformed
        txtEsteh.setText("5000");
    }//GEN-LAST:event_cbkEstehActionPerformed

    private void cbkKopsusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkKopsusActionPerformed
        txtKopsus.setText("10000");
    }//GEN-LAST:event_cbkKopsusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMinuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> cbEsjeruk;
    private javax.swing.JComboBox<String> cbEsteh;
    private javax.swing.JComboBox<String> cbKopsus;
    private javax.swing.JCheckBox cbkEsjeruk;
    private javax.swing.JCheckBox cbkEsteh;
    private javax.swing.JCheckBox cbkKopsus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtEsjeruk;
    private javax.swing.JTextField txtEsteh;
    private javax.swing.JTextField txtKopsus;
    private javax.swing.JTextField txtTotEsjeruk;
    private javax.swing.JTextField txtTotEsteh;
    private javax.swing.JTextField txtTotKopsus;
    private javax.swing.JTextField txtTotalMinuman;
    // End of variables declaration//GEN-END:variables
}
